services:
  presidio-anonymizer:
    image: ${REGISTRY_NAME}${IMAGE_PREFIX}presidio-anonymizer${TAG}
    build:
      context: ./presidio-anonymizer
      args:
        - NAME=presidio-anonymizer
      x-bake:
          platforms:
            - linux/amd64
            - linux/arm64
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
  presidio-analyzer:
    image: ${REGISTRY_NAME}${IMAGE_PREFIX}presidio-analyzer${TAG}
    build:
      context: ./presidio-analyzer
      args:
        - NAME=presidio-analyzer
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      - PORT=5001
    ports:
      - "5002:5001"
  presidio-image-redactor:
    image: ${REGISTRY_NAME}${IMAGE_PREFIX}presidio-image-redactor${TAG}
    build:
      context: ./presidio-image-redactor
      args:
        - NAME=presidio-image-redactor
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64

    environment:
      - PORT=5001
    ports:
      - "5003:5001"
